@startuml
left to right direction
 skinparam interface {
backgroundColor lightgrey
borderColor grey
}
skinparam boundary {
backgroundColor lightgrey
borderColor grey
}
skinparam entity {
backgroundColor #f44336
borderColor #b71c1c
}
skinparam component {
ArrowColor #339900
ArrowFontColor #666666
borderColor #448AFF
}
skinparam agent {
ArrowFontColor #666666
borderColor #999999
}
component "ddemo-component" #FAFAFA{
agent _response as valueelement_response #white
interface set as interfaceValueelement_responseSet
interface change as interfaceValueelement_responseChange #white
interfaceValueelement_responseSet .. valueelement_response #616161
valueelement_response .. interfaceValueelement_responseChange #616161
component ironAjax #white
boundary "fire" as fireFire #64B5F6
component valueObserver #white
boundary "fire-bubble" as firebubbleFireBubble #81C784
agent aProperty as valueelementaproperty #white
interface set as interfaceValueelementapropertySet
interface change as interfaceValueelementapropertyChange #white
interfaceValueelementapropertySet .. valueelementaproperty #616161
valueelementaproperty .. interfaceValueelementapropertyChange #616161
boundary "aProperty" as boundaryValueelementapropertyIn #FFB74D
valueelementaproperty <~ boundaryValueelementapropertyIn #FF5722
agent test as valueelementtest #white
interface set as interfaceValueelementtestSet
interface change as interfaceValueelementtestChange #white
interfaceValueelementtestSet .. valueelementtest #616161
valueelementtest .. interfaceValueelementtestChange #616161
boundary "test" as boundaryValueelementtestIn #FFB74D
valueelementtest <~ boundaryValueelementtestIn #FF5722
agent readonly as valueelementreadonly #white
interface set as interfaceValueelementreadonlySet
interface change as interfaceValueelementreadonlyChange #white
interfaceValueelementreadonlySet .. valueelementreadonly #616161
valueelementreadonly .. interfaceValueelementreadonlyChange #616161
boundary "readonly" as boundaryValueelementreadonlyIn #FFB74D
valueelementreadonly <~ boundaryValueelementreadonlyIn #FF5722
component valueObserver2 #white
component button #white
agent texst as valueelementtexst #white
interface set as interfaceValueelementtexstSet
interface change as interfaceValueelementtexstChange #white
interfaceValueelementtexstSet .. valueelementtexst #616161
valueelementtexst .. interfaceValueelementtexstChange #616161
boundary "texst" as boundaryValueelementtexstOut #FFF176
interfaceValueelementtexstChange ~> boundaryValueelementtexstOut #FF5722
boundary "texst" as boundaryValueelementtexstIn #FFB74D
valueelementtexst <~ boundaryValueelementtexstIn #FF5722
component button #white
component ironAjax #white
component callFunction #white
component valueObserver #white
component valueObserver2 #white
interface func as interfaceFuncCallfunction #red
interfaceFuncCallfunction .. callFunction #616161
agent "_unknown" as valueelement_unknown #red
interface set as interfaceValueelement_unknownSet
interface change as interfaceValueelement_unknownChange #white
interfaceValueelement_unknownSet .. valueelement_unknown #616161
valueelement_unknown .. interfaceValueelement_unknownChange #616161
interfaceFuncCallfunction --> interfaceValueelement_unknownSet #FF6F00
interface observe as interfaceObserveValueobserver #FFF176
valueObserver .. interfaceObserveValueobserver #616161
interfaceObserveValueobserver --> interfaceValueelement_responseSet #FF6F00
interface unknown as interfaceUnknownValueobserver2 #red
interfaceUnknownValueobserver2 .. valueObserver2 #616161
interfaceUnknownValueobserver2 --> interfaceValueelement_responseSet #FF6F00
artifact "this.regularTap()" as regularTap #white
interfaceValueChangedvalueObserver2 --(0 regularTap #4444AA
interface generaterequest as interfaceGeneraterequestironAjax  #white
interfaceGeneraterequestironAjax .. ironAjax #616161
interface response as interfaceResponseironAjax #ECEFF1
ironAjax .. interfaceResponseironAjax #616161
interfaceResponseironAjax --> interfaceValueelement_responseSet #FF6F00
interface valueChanged as interfaceValueChangedvalueObserver #ECEFF1
valueObserver .. interfaceValueChangedvalueObserver #616161
interfaceValueChangedvalueObserver ~> fireFire #FF5722
interfaceValueChangedvalueObserver ~> firebubbleFireBubble #DD2C00
interfaceValueChangedvalueObserver --> interfaceValueelementapropertySet #FF6F00
interfaceValueChangedvalueObserver --> interfaceValueelementtestSet #FF6F00
interface valueChanged as interfaceValueChangedvalueObserver2 #ECEFF1
valueObserver2 .. interfaceValueChangedvalueObserver2 #616161
interfaceValueChangedvalueObserver2 --> interfaceValueelementreadonlySet #FF6F00
interface tap as interfaceTapbutton #ECEFF1
button .. interfaceTapbutton #616161
entity "no Target" as XXXXXnirvanaXXXXX
interfaceValueChangedvalueObserver --->  XXXXXnirvanaXXXXX  #d50000 :--f4
interfaceValueChangedvalueObserver --->  XXXXXnirvanaXXXXX  #d50000 :--kappute-verbindung
interfaceTapbutton --> interfaceGeneraterequestironAjax :connectorButtonRequestAjax
}
@enduml
